

name: deploy-with-push

on:
  push:
    branches: ["main"]
  # schedule:
  #   - cron: "0 23,1,4,8,10,13 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["18.x"]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: install & build
      env:
        TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
        TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }}
      run: |
        npm run i
        npm run build
        npm run build:document:openai
        npm run build:document:vitejs
        npm run build:document:vitepress
    - name: Setup Pages
      uses: actions/configure-pages@v2
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v4
      with:
        # Upload entire repository
        path: './docs/.vitepress/dist/'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
